### PR TITLE
fix: fixed error on deletion of expired sessions, fixes #356

### LINKED ISSUE #356: expired sessions - errors on deletion
When a session is expired it still shows using `./fcli ssc session ls`.
Trying to delete the expired sessions by name. e.g. `./fcli ssc session logout proxySetSession -u <name> -p <pass>` 

this returns to stdout
```
java.lang.IllegalStateException: Error reading session descriptor, please try logging in again
        at com.fortify.cli.common.session.helper.AbstractSessionHelper.lambda$get$0(AbstractSessionHelper.java:51)
        at com.fortify.cli.common.session.helper.AbstractSessionHelper.conditionalThrow(AbstractSessionHelper.java:124)
        at com.fortify.cli.common.session.helper.AbstractSessionHelper.get(AbstractSessionHelper.java:51)
        at com.fortify.cli.common.session.cli.cmd.AbstractSessionLogoutCommand.getJsonNode(AbstractSessionLogoutCommand.java:33)
        at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.run(AbstractOutputCommand.java:33)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2104)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2539)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2531)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2493)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2351)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2495)
        at picocli.CommandLine.execute(CommandLine.java:2248)
        at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:74)
        at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:56)
Caused by: java.lang.IllegalStateException: SSC session 'proxySetSession' cannot be retrieved or has expired, please login again
        at com.fortify.cli.common.session.helper.AbstractSessionHelper.checkNonExpiredSessionAvailable(AbstractSessionHelper.java:130)
        at com.fortify.cli.common.session.helper.AbstractSessionHelper.get(AbstractSessionHelper.java:47)
        ... 11 more
```
when I then run `ls` command again, the deleted session is gone.

Shoul the user be receiving these errors? It does not seem like a defect but as a negative test I don't think this should be printed to stdout.

### PR DESCRIPTION
**Pull request by psmf22**
set failIfUnavailable to false,
logout will now be called for all existing sessions, regardless of expiration status

### CODE REVIEW

File: fcli-core/fcli-common/src/main/java/com/fortify/cli/common/session/cli/cmd/AbstractSessionLogoutCommand.java [hunk 1]
```diff
@@ -30,8 +30,7 @@ public JsonNode getJsonNode() {
         var sessionHelper = getSessionHelper();
         if ( sessionHelper.exists(sessionName) ) {
         	result = sessionHelper.sessionSummaryAsObjectNode(sessionName);
-            logout(sessionName, sessionHelper.get(sessionName, true));
-            // TODO Optionally delete all variables
+            logout(sessionName, sessionHelper.get(sessionName, false));
```
Comment (rsenden) [inline fcli-core/fcli-common/src/main/java/com/fortify/cli/common/session/cli/cmd/AbstractSessionLogoutCommand.java:33]: Probably better to use a try/catch/finally block, to always invoke `getSessionHelper().destroy(sessionName)` even if the `logout` method throws an exception. TBD: throw exception if logout method throws exception, or log a warning?

File: fcli-core/fcli-ssc/src/main/java/com/fortify/cli/ssc/token/helper/SSCTokenConverter.java [hunk 2]
```diff
@@ -36,11 +39,18 @@ public static final char[] toRestToken(char[] token) {
     }
     
     public static final boolean isApplicationToken(String token) {
-        return token.matches("^[\\da-f]{8}(?:-[\\da-f]{4}){3}-[\\da-f]{12}$");
+        return applicationTokenPattern.matcher(token).matches();
     }
     
     private static final String decode(String token) {
-        return new String(Base64.decodeBase64(token), StandardCharsets.UTF_8);
+        return validateApplicationTokenFormat(new String(Base64.decodeBase64(token), StandardCharsets.UTF_8));
```
Comment (rsenden) [inline fcli-core/fcli-ssc/src/main/java/com/fortify/cli/ssc/token/helper/SSCTokenConverter.java:46]: Looks like this method is now only called when decoding a REST token. If the given token is already a REST token, the `toRestToken` method returns the given token as-is, without performing any validation (decode & validate decoded token).
